sources=main.cpp Discovery.cpp Interface.cpp Participant.h Management.cpp Monitoring.cpp Sockets.cpp Tools.cpp Discovery.h Management.h Monitoring.h Sockets.h tools.h Interface.h

main:	$(sources)
	g++ -o main main.cpp -pthread

clean:
	rm main
